authenticating/urls.py
from django.urls import path

from . import views
app_name = "authenticating"

urlpatterns = [
    path("", views.register, name="register"),
    path("login/",views.signin,name = 'signin'),
    path("logout/",views.logout2,name = 'logout'),
    
    
    
]

chat/urls.py
from django.urls import path

from . import views
app_name = "chat"

urlpatterns = [
    path("", views.index, name="index"),
    path("<str:room_name>/", views.room, name="room"),
    
]

justchat/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("chat/", include("chat.urls", namespace='chat')),
    path('', include("authenticating.urls"))
]

authenticating/models.py
from django.db import models

# Create your models here.

chat/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class RoomModel(models.Model):
    name = models.CharField(max_length = 100)
    created_at = models.DateTimeField(auto_now = True,null=True )
    def __str__(self):
        return self.name

class MessageModel(models.Model):
    user = models.ForeignKey(User,on_delete = models.PROTECT, null = True)
    room_name = models.ForeignKey(RoomModel,on_delete = models.PROTECT)
    message = models.TextField(null = True)
    created_at = models.DateTimeField(auto_now = True)
    
    def __str__(self):
        return self.message

authenticating/forms.py
from django import forms
from django.contrib.auth.models import User
class RegisterForm(forms.Form):
    username = forms.CharField(max_length=100)
    password = forms.CharField(max_length=100)
    password2 = forms.CharField(max_length=100)
    
    def clean_password2(self):
        if 'password' in self.cleaned_data:
            password = self.cleaned_data['password']
            password2 = self.cleaned_data['password2']
        if password2 and password == password2:
            return password2
        raise forms.ValidationError('Mat Khau khong khop hoac khong hop le')
    
    def clean_username(self):
        username = self.cleaned_data['username']
        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username
        raise forms.ValidationError('Username đã tồn tại')
    def save(self):
        User.objects.create_user(
            username=self.cleaned_data['username'],
            password = self.cleaned_data['password'],
        )

authenticating/views.py
from django.shortcuts import render, redirect
from .forms import RegisterForm
from django.contrib.auth import authenticate, login, logout
# Create your views here.
def register(request):
    form = RegisterForm()
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('chat:index')
    context = {
        'form':form
    }
    return render(request,'authenticating/register.html',context)

def signin(request):
    next = request.GET.get('next')

    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        next = request.GET.get('next')
        is_auth = authenticate(request,username=username,password=password)
        if is_auth:
            login(request,is_auth)
            if next:
                return redirect(next)
            else:
                return redirect('chat:index')
    context = {}
    return render(request,'authenticating/signin.html',context)
def logout2(request):
    logout(request)
    return redirect('authenticating:signin')

chat/views.py
# views.py
from django.shortcuts import render
from .models import RoomModel, MessageModel
from .consumers import ChatConsumer
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.contrib.auth.models import User
@login_required(login_url=settings.LOGIN_URL)
def index(request): 

    return render(request, "chat/index.html")

@login_required(login_url=settings.LOGIN_URL)
def room(request, room_name):
    name = room_name
    model, created = RoomModel.objects.get_or_create(
            name = name,
            
        )
    
    messages = MessageModel.objects.filter(room_name=model)
    context = {
        'messages':messages,
        "room_name": room_name,
    }
    return render(request, "chat/room.html",context)

authenticating/templates/authenticating/register.html
<a href="{% url 'authenticating:signin' %}">Đăng nhập</a>
<a href="{% url 'authenticating:register' %}">Đăng kí</a>

<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Dky</button>
</form>

authenticating/templates/authenticating/signin.html
<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    </head>
    <body>
        <a href="{% url 'authenticating:register' %}">Đăng kí</a>
        <a href="{% url 'authenticating:signin' %}">Đăng nhập</a>

        <form action="" method="post">
            {% csrf_token %}
            <form>
                <div class="form-group">
                <label for="exampleInputEmail1">Username</label>
                <input type="text" class="form-control" id="exampleInputEmail1"  placeholder="Enter username" name = 'username'>
                </div>
                <div class="form-group">
                <label for="exampleInputPassword1">Password</label>
                <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password" name = 'password'>
                </div>
                <div class="form-group form-check">
                <input type="checkbox" class="form-check-input" id="exampleCheck1">
                <label class="form-check-label" for="exampleCheck1">Check me out</label>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </form>

        <script src="" async defer></script>
    </body>
</html>

chat/templates/chat/index.html
<!-- chat/templates/chat/index.html -->
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Rooms</title>
</head>
<body>
    {% if not request.user.is_authenticated %}
    <a href="{% url 'authenticating:register' %}">Đăng kí</a>
    <a href="{% url 'authenticating:signin' %}">Đăng nhập</a>
    
    {% endif %}
    {% if request.user.is_authenticated %}

    <a href="{% url 'authenticating:logout' %}">Đăng xuất</a>
    {% endif %}


    What chat room would you like to enter?<br>
    <input id="room-name-input" type="text" size="100"><br>
    <input id="room-name-submit" type="button" value="Enter">

    <script>
        document.querySelector('#room-name-input').focus();
        document.querySelector('#room-name-input').onkeyup = function(e) {
            if (e.key === 'Enter') {  // enter, return
                document.querySelector('#room-name-submit').click();
            }
        };

        document.querySelector('#room-name-submit').onclick = function(e) {
            var roomName = document.querySelector('#room-name-input').value;
            window.location.pathname = '/chat/' + roomName + '/';
        };
    </script>
</body>
</html>

chat/templates/chat/room.html
<!-- chat/templates/chat/room.html -->
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Room</title>
</head>

<body>
    <textarea id="chat-log" cols="100" rows="20">
        {% for item in messages %}
        {{item.user.username|safe}}:{{item.message|safe}}
        
        {% endfor %}
    </textarea><br>
    <input id="chat-message-input" type="text" size="100"><br>
    <input id="chat-message-submit" type="button" value="Send">


    {{ room_name|json_script:"room-name" }}
    <script>
        const roomName = JSON.parse(document.getElementById('room-name').textContent);

        const chatSocket = new WebSocket(
            'ws://'
            + window.location.host
            + '/ws/chat/'
            + roomName
            + '/'
        );

        chatSocket.onmessage = function(e) {
            const data = JSON.parse(e.data);
            const chatLog = document.querySelector('#chat-log');
            chatLog.value += (data.message + '\n');
            chatLog.scrollTop = chatLog.scrollHeight; // Cuộn xuống cuối cùng

            console.log(data.message);
        };

        chatSocket.onclose = function(e) {
            console.error('Chat socket closed unexpectedly');
        };

        document.querySelector('#chat-message-input').focus();
        document.querySelector('#chat-message-input').onkeyup = function(e) {
            if (e.key === 'Enter') {  // enter, return
                document.querySelector('#chat-message-submit').click();
            }
        };

        document.querySelector('#chat-message-submit').onclick = function(e) {
            const messageInputDom = document.querySelector('#chat-message-input');
            const message = messageInputDom.value;
            chatSocket.send(JSON.stringify({
                'message': message,
                'room_name':roomName,
            }));
            messageInputDom.value = '';
        };
    </script>
</body>
</html>